[package]
name = "static-context"
version = "0.2.0"
description = "Static contexts in Rust"
authors = ["Douglas Creager <dcreager@dcreager.net>"]
license = "Apache-2.0"
repository = "https://github.com/dcreager/rs-static-context/"
edition = "2018"
